version: '3.5'
networks:
  generator-app-network:
    driver: bridge
    name: generator-app-network
services:
  app:
    container_name: generator-news
    image: generator-app
    command: /opt/init-tasks.sh
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
      - ./provisioning/supervisor.d:/etc/supervisor.d:ro
    networks:
      - generator-app-network
    env_file:
      - provisioning/.env
    depends_on:
      - postgres
  postgres:
    container_name: generator-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: generatedb
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: password
    ports:
      - "6000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - generator-app-network
  nginx:
    container_name: generator-nginx
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./provisioning/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - generator-app-network
    depends_on:
      - app
volumes:
  db-data:
