version: '3.5'
networks:
  generator-app-network:
    driver: bridge
    name: generator-app-network
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - generator-app-network
    command:
      - php artisan cache:clear
    env_file:
      - provisioning/.env
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: generatedb
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: password
    ports:
      - "6000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - generator-app-network
  nginx:
    container_name: generator-nginx
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./provisioning/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - generator-app-network
volumes:
  db-data:
